const plans=[
{type:'choice',name:'초이스130',price:130000,data:'데이터 완전 무제한',desc:'초이스 혜택 선택 가능'},{type:'choice',name:'초이스110',price:110000,data:'데이터 완전 무제한',desc:'초이스 혜택 선택 가능'},{type:'choice',name:'초이스90',price:90000,data:'데이터 완전 무제한',desc:'초이스 혜택 선택 가능'},
{type:'basic',name:'베이직100',price:100000,data:'무제한',desc:'선택약정 25% 적용 가능'},{type:'basic',name:'베이직80',price:80000,data:'무제한',desc:'선택약정 25% 적용 가능'},{type:'basic',name:'베이직110GB',price:69000,data:'110GB',desc:'선택약정 시 51,750원'},{type:'basic',name:'베이직70GB',price:61000,data:'70GB',desc:'실속형'},{type:'basic',name:'베이직50GB',price:55000,data:'50GB',desc:'실속형'},{type:'basic',name:'베이직30GB',price:49000,data:'30GB',desc:'실속형'},
...['69','61','55','49','46','44','42','40','38','36','34','32','30'].map(x=>({type:'yogo',name:'요고'+x,price:+x*1000,data:x==='69'?'무제한':'데이터형',desc:'온라인 무약정 요금제'}))];
const models={fold8:{name:'Galaxy Z Fold8',img:'assets/fold8.webp',desc:'대화면 폴더블 플래그십',prices:{'256GB':2278100,'512GB':2440000}},flip8:{name:'Galaxy Z Flip8',img:'assets/flip8-official.jpg',desc:'컴팩트 폴더블 신제품',prices:{'256GB':1485000,'512GB':1640000}},s26ultra:{name:'Galaxy S26 Ultra',img:'assets/s26ultra.jpg',desc:'갤럭시 플래그십 스마트폰',prices:{'256GB':1698400,'512GB':1848000}},iphone17:{name:'iPhone 17',img:'assets/iphone17.jpg',desc:'Apple iPhone 17',prices:{'256GB':1290000,'512GB':1590000}},iphone17pro:{name:'iPhone 17 Pro',img:'assets/iphone17pro.jpg',desc:'Apple iPhone 17 Pro',prices:{'256GB':1790000,'512GB':2090000}}};
const won=n=>new Intl.NumberFormat('ko-KR').format(Math.round(n))+'원',qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
const menu=qs('.menu-btn');if(menu)menu.onclick=()=>qs('.mobile-nav').classList.toggle('open');
qsa('.filter').forEach(b=>b.onclick=()=>{qsa('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');qsa('#phoneGrid .product-card').forEach(c=>c.style.display=(b.dataset.filter==='all'||c.dataset.brand===b.dataset.filter)?'block':'none')});
function renderPlans(f='all'){const box=qs('#planCards');if(!box)return;box.innerHTML=plans.filter(p=>f==='all'||p.type===f).map(p=>`<article class="plan-card"><span class="ptype">${p.type.toUpperCase()}</span><h3>${p.name}</h3><div class="price">월 ${won(p.price)}</div><p><b>${p.data}</b><br>${p.desc}</p><a href="consult.html?plan=${encodeURIComponent(p.name)}">이 요금제로 상담 →</a></article>`).join('')};renderPlans();qsa('.plan-tab').forEach(b=>b.onclick=()=>{qsa('.plan-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPlans(b.dataset.planfilter)});
function initProduct(){if(!qs('#detailName'))return;const p=new URLSearchParams(location.search),key=p.get('model')||'fold8',m=models[key]||models.fold8;qs('#detailName').textContent=m.name;qs('#detailImage').src=m.img;qs('#detailDesc').textContent=m.desc+' · 옵션 선택 후 예상 월 납부금을 확인하세요.';const st=qs('#storage');st.innerHTML=Object.keys(m.prices).map(x=>`<option>${x}</option>`).join('');const mp=qs('#mobilePlan');mp.innerHTML=plans.filter(x=>x.type!=='yogo').map(x=>`<option value="${x.price}">${x.name} · 월 ${won(x.price)}</option>`).join('');function calc(){let device=m.prices[st.value],months=+qs('#installment').value,plan=+mp.value,discount=qs('#discountType').value,combine=+qs('#combine').value;if(discount==='select')plan*=.75;const dm=device/months,total=dm+plan-combine;qs('#monthlyTotal').textContent='월 '+won(total)+'~';qs('#priceBreakdown').textContent=`단말 약 ${won(dm)} + 요금제 약 ${won(plan)}${combine?` - 결합 예시 ${won(combine)}`:''}`};qsa('#storage,#mobilePlan,#discountType,#installment,#combine').forEach(x=>x.onchange=calc);calc();qs('#productConsult').onclick=()=>{const data={model:m.name,storage:st.value,join:qs('#joinType').value,plan:mp.options[mp.selectedIndex].text,discount:qs('#discountType').options[qs('#discountType').selectedIndex].text,installment:qs('#installment').value+'개월',combine:qs('#combine').options[qs('#combine').selectedIndex].text,estimate:qs('#monthlyTotal').textContent};location.href='consult.html?'+new URLSearchParams(data)}}initProduct();
function initInternet(){if(!qs('#inetSpeed'))return;function c(){const a=+qs('#inetSpeed').value,b=+qs('#tvPlan').value,w=qs('#wifi').checked?2200:0;qs('#inetTotal').textContent='월 '+won(a+b+w)+'~';qs('#inetSummary').innerHTML=`<p>인터넷 ${won(a)}<br>TV ${won(b)}<br>Wi-Fi ${won(w)}</p>`}qsa('#inetSpeed,#tvPlan,#wifi,#mobileCombine').forEach(x=>x.onchange=c);c();qs('#internetConsult').onclick=()=>{const t=`인터넷 ${qs('#inetSpeed').options[qs('#inetSpeed').selectedIndex].text}, TV ${qs('#tvPlan').options[qs('#tvPlan').selectedIndex].text}, Wi-Fi ${qs('#wifi').checked?'포함':'미포함'}, 휴대폰결합 ${qs('#mobileCombine').checked?'상담':'없음'}, ${qs('#inetTotal').textContent}`;location.href='consult.html?type=internet&conditions='+encodeURIComponent(t)}}initInternet();
function initConsult(){const model=qs('#consultModel');if(!model)return;const p=new URLSearchParams(location.search),map={fold8:'Galaxy Z Fold8',flip8:'Galaxy Z Flip8',s26ultra:'Galaxy S26 Ultra',iphone17:'iPhone 17',iphone17pro:'iPhone 17 Pro'};if(p.get('model'))model.value=map[p.get('model')]||p.get('model');if(p.get('type')==='internet')model.value='인터넷·TV';if(p.get('join'))qs('#consultJoin').value=p.get('join');const cond=[];['storage','plan','discount','installment','combine','estimate','conditions'].forEach(k=>{if(p.get(k))cond.push(`${k}: ${p.get(k)}`)});qs('#selectedConditions').value=cond.join(' / ')}initConsult();
